version: '3.8'

services:
  ai:
    build: .
    container_name: xywpgx-ai
    ports:
      - "8088:8088"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_NACOS_CONFIG_USERNAME=nacos
      - SPRING_CLOUD_NACOS_CONFIG_PASSWORD=zhoujiadayuan
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos:8848
      - SPRING_CLOUD_NACOS_DISCOVERY_USERNAME=nacos
      - SPRING_CLOUD_NACOS_DISCOVERY_PASSWORD=zhoujiadayuan
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR=nacos:8848
    networks:
      - micro-net
    restart: unless-stopped

networks:
  micro-net:
    external: true